
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMESop : calcop : op PLUS calcop : op MINUS calccalc : exprcalc : calc TIMES exprcalc : calc DIVIDE exprexpr : NUMBERexpr : LPAREN op RPAREN'
    
_lr_action_items = {'NUMBER':([0,5,6,7,8,9,],[4,4,4,4,4,4,]),'LPAREN':([0,5,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,4,11,12,13,14,15,],[0,-1,-4,-7,-2,-3,-5,-6,-8,]),'PLUS':([1,2,3,4,10,11,12,13,14,15,],[6,-1,-4,-7,6,-2,-3,-5,-6,-8,]),'MINUS':([1,2,3,4,10,11,12,13,14,15,],[7,-1,-4,-7,7,-2,-3,-5,-6,-8,]),'RPAREN':([2,3,4,10,11,12,13,14,15,],[-1,-4,-7,15,-2,-3,-5,-6,-8,]),'TIMES':([2,3,4,11,12,13,14,15,],[8,-4,-7,8,8,-5,-6,-8,]),'DIVIDE':([2,3,4,11,12,13,14,15,],[9,-4,-7,9,9,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'op':([0,5,],[1,10,]),'calc':([0,5,6,7,],[2,2,11,12,]),'expr':([0,5,6,7,8,9,],[3,3,3,3,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> op","S'",1,None,None,None),
  ('op -> calc','op',1,'p_op_1','calc_yacc.py',5),
  ('op -> op PLUS calc','op',3,'p_op_2','calc_yacc.py',9),
  ('op -> op MINUS calc','op',3,'p_op_3','calc_yacc.py',13),
  ('calc -> expr','calc',1,'p_calc_1','calc_yacc.py',19),
  ('calc -> calc TIMES expr','calc',3,'p_calc_2','calc_yacc.py',23),
  ('calc -> calc DIVIDE expr','calc',3,'p_calc_3','calc_yacc.py',27),
  ('expr -> NUMBER','expr',1,'p_expr_1','calc_yacc.py',32),
  ('expr -> LPAREN op RPAREN','expr',3,'p_expr_2','calc_yacc.py',36),
]
